export interface Karyawan {
  id: number;
  kode: string;
  nama: string;
  tanggal_mulai: string;
  tanggal_habis: string;
  created_at: string;
  updated_at: string;
}

/** Used when creating a new record – kode is generated by the backend. */
export interface KaryawanCreateRequest {
  nama: string;
  tanggal_mulai: string;
  tanggal_habis: string;
}

/** Used when updating an existing record – kode can be edited. */
export interface KaryawanUpdateRequest {
  kode: string;
  nama: string;
  tanggal_mulai: string;
  tanggal_habis: string;
}

/** @deprecated Use KaryawanCreateRequest or KaryawanUpdateRequest instead. */
export type KaryawanRequest = KaryawanUpdateRequest;

export interface ImportError {
  row: number;
  field: string;
  message: string;
}

export interface ApiResponse<T = unknown> {
  message: string;
  data?: T;
  errors?: Record<string, string> | string | ImportError[];
}
